### ISSUE TITLE
chalk.constructor is not a constructor

### ISSUE THREAD

**Issue by UPDOWNUP-64BIT** [davidlimjh/TatsuBot#6]
ypeError: chalk.constructor is not a constructor
    at Object.<anonymous> (C:\Users\Documents\ff\TatsuBot\BrussellBot.js:14:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by UPDOWNUP-64BIT** [comment]
Fixed

**Comment by AsadxNaeem** [comment]
@UPDOWNUP Up How did you fix it. Please Share the Solution to this Problem. I am encountering the same error.

**Comment by AsadxNaeem** [comment]
> Fixed
@UpDownUp Up How did you fix it. Please Share the Solution to this Problem. I am encountering the same error.

**Comment by Mckiba** [comment]
> Fixed
> @UpDownUp Up How did you fix it. Please Share the Solution to this Problem. I am encountering the same error.



> Fixed
> @UpDownUp Up How did you fix it. Please Share the Solution to this Problem. I am encountering the same error.

Hey I'm having the same problem. Do you mind sharing your solution?
